services:
  cache:
    image: varnish
    command: varnishd -f /etc/varnish/default.vcl -F -s file,/storage,10G
    ports:
      - 8080:80
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    volumes:
      - ./cache/default.vcl:/etc/varnish/default.vcl:ro
      - ./cache/storage:/storage
  auth:
    build: ./auth
    ports: 
      - 80:8080
    environment:
      HOSTNAME: cache
  fetch:
    build: ./fetch
    ports:
      - 8081:80
    volumes:
      - ./fetch/nginx.conf:/etc/nginx/nginx.conf:ro
  oidc:
    image: soluto/oidc-server-mock
    ports:
      - "8082:80"
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        API_RESOURCES_INLINE: |
          [
            {name: "cache", scopes: ["cache"]}
          ]
        API_SCOPES_INLINE: |
          [
            {name: "cache"}
          ]
        CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
    volumes:
      - ./oidc:/tmp/config:ro
